repos:
# - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.3.0
#     hooks:
#     - id: trailing-whitespace
#     - id: end-of-file-fixer
#     - id: check-yaml
#     - id: requirements-txt-fixer
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout
